config/routes.rb
Rails.application.routes.draw do

  root :to => 'messages#index'

  resources :messages

  get 'outbox', to: 'messages#outbox'
  post 'reply_to_admin', to: 'messages#reply_to_admin'
  post 'admin_message', to: 'messages#admin_message'
  get 'get_all_inbox', to: 'messages#get_all_inbox'
  get 'get_all_outbox', to: 'messages#get_all_outbox'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/message.rb
class Message < ApplicationRecord

  after_save :update_inbox_unread

  belongs_to :inbox
  belongs_to :outbox

  before_create do
    self.read = false
  end

  private
  def update_inbox_unread
    if self.read
      # If a message is set to "read", decrement the count
      self.inbox.unread_count = self.inbox.unread_count - 1
    else
      # If a message is set to "unread", increment the count
      if self.inbox.unread_count
        self.inbox.unread_count = self.inbox.unread_count + 1
      else
        self.inbox.unread_count = 1
      end
    end
    self.inbox.save
  end

end

app/models/outbox.rb
class Outbox < ApplicationRecord

  belongs_to :user
  has_many :messages

end

app/models/payment.rb
class Payment < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_one :inbox
  has_one :outbox
  has_many :payments
  has_many :messages

  scope :patient, -> { where(is_patient: true) }
  scope :admin, -> { where(is_admin: true) }
  scope :doctor, -> { where(is_doctor: true) }

  def self.current
    User.patient.first
  end

  def self.default_admin
    User.admin.first
  end

  def self.default_doctor
    User.doctor.first
  end

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @messages = Message.where(inbox: User.current.inbox).limit(10)
  end

  def get_all_inbox
    @messages = Message.where(inbox: User.current.inbox).offset(10)
  end

  def get_all_outbox
    @messages = Message.where(outbox: User.current.outbox).offset(10)
  end

  def show
    @message = Message.find(params[:id])
    if @message.inbox == User.current.inbox
      if !@message.read
        @message.read = true
        @message.save
      end
    end

    @reply_to_admin = (Date.today - @message.created_at.to_date > 7)
  end

  def new
    @message = Message.new
  end

  def outbox
    @messages = Message.where(outbox: User.current.outbox).limit(10)
  end

  def admin_message
    @provider = PaymentProviderFactory.new
    @provider.debit_card(User.current)
    @payment = Payment.new
    @payment.user = User.current
    @payment.save
    @message = Message.new
    @message.body = `Issue a new prescription for #{User.current.full_name}`
    @message.outbox = User.current.outbox
    @message.inbox = User.default_admin.inbox
    # @message.read = false
    if @payment.save
      @message = Message.new
      @message.body = `Issue a new prescription for #{User.current.full_name}`
      @message.outbox = User.current.outbox
      @message.inbox = User.default_admin.inbox
      @message.save
      render json: { text: "Message sent", status: 200 }
    else
      render json: { text: "Something went wrong. Please retry."}, status: 500
    end
  end

  def create
    doctor = User.default_doctor
    @message = Message.new
    @message.body = params[:message][:body]
    @message.outbox = User.current.outbox

    @message.inbox = doctor.inbox

    if @message.save
      redirect_to @message
    else
      redirect_to :action => 'new'
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NuaMessaging</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-light">
    <%= render 'navigation/header' %>

    <main role="main" class="container">
      <%= yield %>
    </main>
  </body>
</html>

app/views/messages/_message.html.erb
<%= link_to message do %>
  <div class="media text-muted pt-3">
    <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"></rect><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
      <strong class="d-block text-gray-dark">
        From: <%= message.outbox.user.first_name %> <%= message.outbox.user.last_name %>
      </strong>
      <% if message.body %>
        <%= message.body.truncate(45) %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/messages/get_all_inbox.js.erb
$('[data-action="messages"]').append('<%= escape_javascript render(@messages) %>');

app/views/messages/get_all_outbox.js.erb
$('[data-action="messages"]').append('<%= escape_javascript render(@messages) %>');

app/views/messages/index.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Inbox</h6>
  <div class="message-container" data-action="messages">
    <% if @messages.count > 0 %>
      <%= render partial: "message", collection: @messages %>
    <% else %>
      <h4>No messages here!</h4>
    <% end %>
  </div>

  <small class="d-block text-right mt-3">
    <%= link_to get_all_inbox_path, remote: true do %>All updates<% end %>
  </small>
</div>

app/views/messages/new.html.erb
<div class="card mt-3">
  <h5 class="card-header">
    New Message
  </h5>

  <div class="card-body">
    <%= form_for @message do |f| %>
      <div class="form-group py-3">
        <%= f.text_area :body, class: "form-control", rows: 3, required: true %>
      </div>

      <div class="form-group mb-0 text-right">
        <%= f.submit 'Send Message', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/outbox.html.erb
<div class="my-3 p-3 bg-white rounded shadow-sm">
  <h6 class="border-bottom border-gray pb-2 mb-0">Outbox</h6>
  <% if @messages.count > 0 %>
    <%= render partial: "message", collection: @messages %>
  <% else %>
    <h4>No messages here!</h4>
  <% end %>
  <small class="d-block text-right mt-3">
    <%= link_to get_all_outbox_path, remote: true do %>All updates<% end %>
  </small>
</div>

app/views/messages/show.html.erb
<div class="card my-3 ">
  <h5 class="card-header">
    <% if @message.outbox.user.is_doctor? %>Dr.<% end %>
    <%= @message.outbox.user.full_name %>
  </h5>
  <div class="card-body">
    <p class="card-text"><%= @message.body %></p>
    <%= link_to new_message_path, class: "btn btn-primary" do %>
      <% if @reply_to_admin %>
        Reply to admin
      <% else %>
        Reply
      <% end %>
    <% end %>
    <% if @message.inbox == User.current.inbox %>
      <%= link_to admin_message_path, remote: true, method: 'post', class: 'btn btn-primary', data: { action: 'admin-button' } do %>
        <span class="text">I've lost my script, please issue a new one at a charge of €10</span>
        <span class="lds-dual-ring d-none loader"></span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/navigation/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Nua Messaging</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to messages_path, class: 'nav-link' do %>
          Inbox <% if User.current.inbox.unread_count > 0 %><span class="badge badge-secondary"><%= User.current.inbox.unread_count %></span><% end %>
        <% end  %>
      </li>
      <li class="nav-item active">
        <%= link_to outbox_path, class: 'nav-link' do %>
          Outbox
        <% end  %>
      </li>
    </ul>
  </div>
</nav>